### ISSUE TITLE
Source control section is missing on gitbook

### ISSUE THREAD

**Issue by Yeldece** [grofit/development-for-winners#4]
Hello,
In the gitbook version of this repo, source control section is all blank.
EG see: https://grofit.gitbook.io/development-for-winners/development/general/source-control/source-control-basics

**Comment by grofit** [comment]
Hey, will look into it tomorrow, I know gitbook did a whole new version update a while back which caused urls to change etc, but as long as the summary.md points to the right file it should be fine.

**Comment by grofit** [comment]
Should all be fixed now, the paths were wrong in the summary file.
